### PR TITLE
fix: issue 128 - Added sanitization for guid

### LINKED ISSUE #128: Attempting to get URI in RequestInformation, results in an error when one of the query parameters is a Guid
(This is a similar issue to https://github.com/microsoft/kiota-abstractions-dotnet/issues/127, but I felt it was better raised separately)

I am using Microsoft Kiota to generate an API client from an open api yaml file. In this file, one of the request parameters is a guid
```
- name: TenantId
  in: query
  required: true
  schema:
    type: string
    format: uuid
```
This was working fine when the generated API client was using version 1.3.1 of Microsoft.Kiota.Abstractions. However, when upgrading to 1.3.2, when attempting to access the URI property results in an error.

Here is a sample C# console app (target framework net7.0, running on Windows 10), using code I extracted from the generated API client
```
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Authentication;
using Microsoft.Kiota.Http.HttpClientLibrary;

namespace Kiota;

public class Program
{
    static void Main(string[] args)
    {
        var pathParameters = new Dictionary<string, object>
        {
            { "baseurl", "http://localhost:123" }
        };
        var requestAdapter = new HttpClientRequestAdapter(new AnonymousAuthenticationProvider())
        {
            BaseUrl = "http://localhost:123"
        };
        var requestBuilder = new TestRequestBuilder(pathParameters, requestAdapter);

        var queryParms = new TestRequestBuilder.TestRequestBuilderGetQueryParameters
        {
            TenantId = Guid.NewGuid()
        };

        var requestInfo = requestBuilder.ToGetRequestInformation(x => x.QueryParameters = queryParms);
        Console.Write(requestInfo.URI.ToString());
    }
}

public class TestRequestBuilder : BaseRequestBuilder
{
    public TestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/Test{?tenantId*}", pathParameters)
    {
    }

    public class TestRequestBuilderGetQueryParameters
    {
        [QueryParameter("tenantId")]
        public Guid TenantId { get; set; }
    }

    public class TestBuilderGetRequestConfiguration
    {
        public RequestHeaders Headers { get; set; }
        public IList<IRequestOption> Options { get; set; }
        public TestRequestBuilderGetQueryParameters QueryParameters { get; set; } = new TestRequestBuilderGetQueryParameters();

        public TestBuilderGetRequestConfiguration()
        {
            Options = new List<IRequestOption>();
            Headers = new RequestHeaders();
        }
    }

    public RequestInformation ToGetRequestInformation(Action<TestBuilderGetRequestConfiguration>? requestConfiguration = default)
    {
        var requestInfo = new RequestInformation
        {
            HttpMethod = Method.GET,
            UrlTemplate = UrlTemplate,
            PathParameters = PathParameters,
        };
        requestInfo.Headers.Add("Accept", "application/problem+json");
        if (requestConfiguration != null)
        {
            var requestConfig = new TestBuilderGetRequestConfiguration();
            requestConfiguration.Invoke(requestConfig);
            requestInfo.AddQueryParameters(requestConfig.QueryParameters);
            requestInfo.AddRequestOptions(requestConfig.Options);
            requestInfo.AddHeaders(requestConfig.Headers);
        }
        return requestInfo;
    }
}
```
With 1.3.1, the uri is generated as http://localhost:123/api/v1/Test?TenantId=8d20c652-1466-444f-af2a-403a03476187

With 1.3.2 when attempting to write the uri to the console, the following error is thrown
`System.ArgumentException: 'Illegal class passed as substitution, found System.Guid at col:33'`

Note: If I change the type to string in the above code, then it works successfully

### PR DESCRIPTION
**Pull request by timandella**
Added sanitization for guid to fix issue 128
Fixes #128

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Thanks for the contribution. Can you add an entry in the changelog as well please?

**Comment by timandella** [comment]
Added a change log

**Comment by timandella** [comment]
Merge conflict resolved

**Review by andrueastman — APPROVED** [review]
Thanks for the contribution @timandella

**Pull request merged**
