### PR TITLE
When MultipartBody is serialized the values are generated with CRLF

### PR DESCRIPTION
**Pull request by MartinM85**
Fix for #247

### CODE REVIEW

**Comment by andrueastman** [comment]
Any chance we can clarify things out in the issue at https://github.com/microsoft/kiota-abstractions-dotnet/issues/247 first?
I believe there is a possibility that no action is needed here..

**Comment by MartinM85** [comment]
@andrueastman You are right, with `text/plain` everything works fine in the latest version. Not sure why I was using `application/x-www-form-urlencoded`

**Comment by andrueastman** [comment]
@MartinM85 Thanks for confirming. I think we can close this one for now.

If it makes sense, the next action steps would be looking into whether we need to make a change in the `application/x-www-form-urlencoded` serialization writer as highlighted in https://github.com/microsoft/kiota-abstractions-dotnet/issues/247

**Comment by andrueastman** [comment]
Closing this one for now to follow up on #247

**Pull request closed without merging**
