### PR TITLE
Use TryAdd when setting Content-Type

### PR DESCRIPTION
**Pull request by andreaTP**
Forgot to actually use `TryAdd` ...

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
Any chance you can add a version bump and changelog entry as well to release?
Otherwise, looks good to me 👍🏼

**Comment by andreaTP** [comment]
> Any chance you can add a version bump and changelog entry as well to release?

I can, but I thought what I have added yesterday is already enough, let me know if I should do it anyhow!

**Comment by andrueastman** [comment]
I think we should just do it. I believe the interaction with the `SetStreamContent` and other methods would be incongruent with what we are trying to achieve at https://github.com/microsoft/kiota/issues/3378 if we don't release the change.

**Review by baywet — CHANGES_REQUESTED** [review]
Yes we'll need a new release since the other one was published

**Comment by andreaTP** [comment]
It's a holiday today, I'll make the changes tomorrow :+1:

**Review by baywet — APPROVED** [review]
@AndreaTP no worries, enjoy your time off, I've just pushed the changes

**Review by baywet — APPROVED** [review]

**Pull request merged**
