### PR TITLE
Upgrade the `Std.UriTemplate` lib to 0.54 and add a unit test.

### PR DESCRIPTION
**Pull request by IEvangelist**
Upgrade the `Std.UriTemplate` lib to 0.54 and add a unit test.

Related to observed behavior here: https://github.com/std-uritemplate/std-uritemplate/issues/114

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
it's strange that dependabot didn't pick it up for us...
Can you also bump the patch and add a changelog entry (tomorrow, changed) so we can expedite the release please?

**Comment by andrueastman** [comment]
Just to confirm, dependabot updated the dependency via https://github.com/microsoft/kiota-abstractions-dotnet/pull/203. We just need to release a new update to abstractions with the new dependency.
@IEvangelist Any chance you can make sure you rebase/sync your branch as well?

**Comment by IEvangelist** [comment]
Done

**Review by baywet — CHANGES_REQUESTED** [review]
I think we lost the version bump in the csproj somehow

**Review by andrueastman — APPROVED** [review]

**Comment by IEvangelist** [comment]
Tagging @nickfloyd, you're going to want to upgrade to whatever version this ships in for the Ocokit .NET SDK.

**Pull request merged**
